# Generated by Django 4.1.1 on 2022-09-17 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='description',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
