# Generated by Django 4.1.1 on 2022-09-17 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0004_rename_comment_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='usercomment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='libraryapp.video'),
        ),
    ]
