# Generated by Django 4.1.1 on 2022-09-17 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0005_alter_comments_usercomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='visitorspost',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='libraryapp.video'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='usercomment',
            field=models.CharField(max_length=275, null=True),
        ),
    ]
