# Generated by Django 4.1.1 on 2022-09-17 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0006_comments_visitorspost_alter_comments_usercomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='usercomment',
            new_name='visitorscomment',
        ),
    ]
