# Generated by Django 4.1.1 on 2022-09-18 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0007_rename_usercomment_comments_visitorscomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
